name: Project Building
on:
  push:
    paths: ['cat2/**', '.github/workflows/Build.yml']
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/cache@main
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
          restore-keys: nuget-${{ runner.os }}-
      - run: dotnet publish -r win-x64 -c ${{ matrix.configuration }} /p:PublishSingleFile=true --self-contained false
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.configuration }}
          path: '**/publish/'
